### ISSUE TITLE
Windows build issue, "undefined RestoreAsset"

### ISSUE THREAD

**Issue by alexmipego** [progrium/go-basher#22] opened 2019-09-03 16:15 UTC
I'm trying to build a small tool and cross compile it for Windows, however go-basher is giving me this issue:

```
$ GOOS=windows GOARCH=amd64 go build main.go 
# github.com/progrium/go-basher
../../../../../go/src/github.com/progrium/go-basher/basher.go:52:9: undefined: RestoreAsset
```

Builds for Linux and OSX seem to work fine, and go run main.go also runs fine. Do you have any insight on how to solve this?

**Comment by josegonzalez** [comment] 2019-09-03 16:59
I think its in the bindata for Darwin and Linux, based on [this commit](https://github.com/progrium/go-basher/commit/079a04f4728ce007d21a414bd1f4ef60110fe0d0). Not sure where to go from there though.

**Comment by lalyos** [comment] 2023-09-14 16:59
The problem is that there are 2 different go-bindata:
- https://github.com/a-urth/go-bindata (this is needed for this project)
- https://github.com/jteeuwen/go-bindata (other)

Yo have probably the other already on your PATH

btw it could be replaced with go:embed anyways

**Comment by josegonzalez** [comment] 2023-09-17 01:49
Happy to take PRs fixing this :)

**Comment by lalyos** [comment] 2023-09-17 18:13
I've looked it again, and actually this issue can be closed as there is no windows support at all. 

The whole idea is to take the os/arch specific static single binary bash from https://github.com/robxu9/bash-static/ and embed it. But https://github.com/robxu9/bash-static/ itself only supports mac and linux.

Regarding the conflicting go-bindata packages, I found an other issue. Will open separately.

**Closed as completed** 2023-09-23 04:42 UTC
